name: Test Bisection Feature

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest-reportlog
        run: |
          pytest --report-log=pytest-log.jsonl -v

      - name: Use issue-from-pytest-log-action with bisection
        if: always() # Run regardless of test outcome to store data
        uses: ianhi/issue-from-pytest-log-action@bisect
        with:
          log-path: pytest-log.jsonl
          track-packages: "numpy,requests,pytest,hypothesis,pandas,matplotlib"
          python-command: "python"
          bisect-branch: "bisect-data"
          issue-title: "🔍 Test Bisection Demo - Failed Tests"
          issue-label: "bisection-demo"

