name: Demonstrate Test Failures

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      make_tests_fail:
        description: 'Make some tests fail to demonstrate bisection'
        required: true
        default: 'true'
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Modify test to simulate failures
        if: ${{ inputs.make_tests_fail == true }}
        run: |
          # Modify the test file to make some tests fail
          sed -i 's/SHOULD_PASS = True/SHOULD_PASS = False/' test_sample.py
          sed -i 's/# assert False, f"Parameter {value} configured to fail"/assert False, f"Parameter {value} configured to fail"/' test_sample.py

      - name: Show what tests will run
        run: |
          echo "Test file contents:"
          cat test_sample.py
          echo ""
          echo "Installed packages:"
          pip list

      - name: Run tests with pytest-reportlog
        run: |
          pytest --report-log=pytest-log.jsonl -v
        continue-on-error: true

      - name: Show pytest log
        run: |
          echo "Pytest log contents:"
          cat pytest-log.jsonl

      - name: Use issue-from-pytest-log-action with bisection
        if: always()
        uses: scientific-python/issue-from-pytest-log-action@main
        with:
          log-path: pytest-log.jsonl
          track-packages: "numpy,requests,pytest,pip,setuptools"
          issue-title: "🐛 Intentional Test Failures - Bisection Demo"
          issue-label: "bisection-demo"
          bisect-branch: "bisection-data"